matrix:
  include:
  - language: ruby
    rvm: 2.4.1
    script: scripts/run_ruby_tests.sh
    services:
    - mysql
  - language: node_js
    node_js: 8
    script: scripts/run_node_tests.sh
  - language: ruby
    rvm: 2.4.1
    script: scripts/run_feature_tests.sh
    services:
    - mysql